"""Shared test fixtures and configuration for radar tests."""
import pytest
import sqlite3
import tempfile
import shutil
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock
from radar.models import (
    SourceConfig, StackConfig, PostingConfig, RawItem, ScoredItem, GeneratedPost
)


@pytest.fixture
def temp_dir():
    """Create a temporary directory for tests."""
    temp_path = tempfile.mkdtemp()
    yield Path(temp_path)
    shutil.rmtree(temp_path)


@pytest.fixture
def temp_sqlite_path(temp_dir):
    """Create a temporary SQLite database path."""
    return str(temp_dir / "test.db")


@pytest.fixture
def mock_source_config():
    """Create a mock source configuration."""
    return SourceConfig(
        id="test_source",
        type="github_releases",
        repo="test/repo",
        tags=["test", "ai"],
        priority=3
    )


@pytest.fixture
def mock_webpage_source_config():
    """Create a mock webpage source configuration."""
    return SourceConfig(
        id="test_webpage",
        type="webpage_diff",
        url="https://example.com",
        tags=["test"],
        priority=3
    )


@pytest.fixture
def mock_stack_config():
    """Create a mock stack configuration."""
    return StackConfig(
        stack_slug="test_stack",
        title="Test Stack",
        timezone="UTC",
        languages=["en", "de"],
        posting=PostingConfig(
            generate_de_if_impact_gte=70,
            medium_if_impact_gte=70,
            post_if_impact_gte=40
        ),
        sources=[
            SourceConfig(
                id="test_source",
                type="github_releases",
                repo="test/repo",
                tags=["test"],
                priority=3
            )
        ]
    )


@pytest.fixture
def mock_raw_item():
    """Create a mock raw item."""
    return RawItem(
        source_id="test_source",
        kind="release",
        external_id="v1.0.0",
        title="Test Release",
        url="https://github.com/test/repo/releases/tag/v1.0.0",
        published_at="2024-01-01T00:00:00Z",
        raw_text="This is a test release with breaking changes",
        raw_hash="test_hash_123",
        metadata={"tags": ["test"], "priority": 3}
    )


@pytest.fixture
def mock_scored_item():
    """Create a mock scored item."""
    return ScoredItem(
        raw=RawItem(
            source_id="test_source",
            kind="release",
            external_id="v1.0.0",
            title="Test Release",
            url="https://github.com/test/repo/releases/tag/v1.0.0",
            published_at="2024-01-01T00:00:00Z",
            raw_text="This is a test release with breaking changes",
            raw_hash="test_hash_123",
            metadata={"tags": ["test"], "priority": 3}
        ),
        impact_score=75,
        flags=["breaking"],
        tags=["test"]
    )


@pytest.fixture
def mock_generated_post():
    """Create a mock generated post."""
    return GeneratedPost(
        source_id="test_source",
        external_id="v1.0.0",
        kind="release",
        url="https://github.com/test/repo/releases/tag/v1.0.0",
        impact_score=75,
        flags=["breaking"],
        tags=["test"],
        languages=["en", "de"],
        title_en="Test Release (impact 75)",
        hook_en="Quick summary generated by MockLLM.",
        short_en="TL;DR: This is a placeholder short post.\n\nSource: https://github.com/test/repo/releases/tag/v1.0.0",
        medium_en=None,
        title_de="Test Release (Impact 75)",
        hook_de="Kurze Zusammenfassung (Mock).",
        short_de="TL;DR: Platzhalter.\n\nQuelle: https://github.com/test/repo/releases/tag/v1.0.0",
        medium_de=None,
        action_items=["Review the release notes.", "Test in staging."],
        sources=["https://github.com/test/repo/releases/tag/v1.0.0"],
        confidence="low"
    )


@pytest.fixture
def mock_llm():
    """Create a mock LLM client."""
    llm = AsyncMock()
    llm.generate_post_json = AsyncMock(return_value={
        "title": "Test Post (impact 50)",
        "hook": "Test hook",
        "short": "Test short summary",
        "medium": None,
        "action_items": ["Test action"],
        "sources": ["https://example.com"],
        "confidence": "medium"
    })
    return llm


@pytest.fixture
def mock_httpx_client():
    """Create a mock httpx client."""
    client = AsyncMock()
    client.get.return_value.raise_for_status.return_value = None
    client.get.return_value.json.return_value = [
        {
            "tag_name": "v1.0.0",
            "name": "Test Release",
            "body": "This is a test release",
            "html_url": "https://github.com/test/repo/releases/tag/v1.0.0",
            "published_at": "2024-01-01T00:00:00Z",
            "draft": False
        }
    ]
    client.get.return_value.text = "<html><body>Test page content</body></html>"
    return client


@pytest.fixture
def sample_stack_yaml_content():
    """Sample stack.yaml content for testing."""
    return """
stack_slug: test_stack
title: Test Stack
timezone: UTC
languages:
  - en
  - de
posting:
  generate_de_if_impact_gte: 70
  medium_if_impact_gte: 70
  post_if_impact_gte: 40
sources:
  - id: test_source
    type: github_releases
    repo: test/repo
    tags:
      - test
      - ai
    priority: 3
  - id: test_webpage
    type: webpage_diff
    url: https://example.com
    tags:
      - webpage
    priority: 2
"""