from radar.llm.base import LLMClient
from typing import List

class MockLLM(LLMClient):
    async def generate_post_json(self, *, raw_text: str, title: str, url: str, impact_score: int, flags: List[str], lang: str) -> dict:
        if lang == "en":
            return {
                "title": f"{title} (impact {impact_score})",
                "hook": "English summary generated by MockLLM.",
                "short": "TL;DR: This is a placeholder short post.\n\nSource: " + url,
                "medium": None,
                "action_items": ["Review the release notes.", "Test in staging."],
                "sources": [url],
                "confidence": "low",
            }
        return {
            "title": f"{title} (Impact {impact_score})",
            "hook": "Kurze Zusammenfassung (Mock).",
            "short": "TL;DR: Platzhalter.\n\nQuelle: " + url,
            "medium": None,
            "action_items": ["Release Notes lesen.", "In Staging testen."],
            "sources": [url],
            "confidence": "low",
        }